apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: upnp-server
    tier: frontend
    track: stable
spec:
  containers:
    - name: upnp-server-frontend
      image: lucifiel1618/pyupnp-server:amd64
      # imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: media-disk
          mountPath: /pyupnp-server/media/disk
          readOnly: true
      resources:
      # Resource request and limits apply to each container,
      # not to the whole Job
        requests:
          cpu: 500m
          memory: 1000Mi
        limits:
          cpu: 4000m
          memory: 1000Mi
      ports:
        - name: http
          containerPort: 9000
          hostPort: 9000
  volumes:
  - name: media-disk
    persistentVolumeClaim:
      claimName: upnp-server-pvc