apiVersion: v1
kind: PersistentVolume
metadata:
  name: upnp-server-pv
spec:
  capacity:
    storage: 100Gi # Adjust the storage size as needed
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.1.111
    path: /nfs/luc/Downloads/
  mountOptions:
    - nolock
  # local:
  #   path: /Volumes/Public/Projects/brown-panda-breeding/manifests/prod/data